# Generated by Django 5.0.4 on 2024-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususer',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attemptedquizbyanonymoususer',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
