# Generated by Django 5.0.4 on 2024-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_multiplechoiceoption_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedquizbyanonymoususer',
            name='questions_attempted',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.question'),
        ),
    ]
