# Generated by Django 5.0.4 on 2024-04-23 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('multiple_selection', models.BooleanField(default=True)),
                ('vertical_alignment', models.BooleanField(default=False)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('randomize', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('seperator', models.TextField(choices=[('-', '-'), ('.', '.'), ('/', '/')], default='/', max_length=30)),
                ('format', models.TextField(choices=[('yyyy-MM-dd', 'yyyy-MM-dd'), ('dd-MM-yyyy', 'dd-MM-yyyy'), ('MM-yyyy-dd', 'MM-yyyy-dd'), ('PPP', 'PPP')], default='dd-MM-yyyy', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('alphabetically', models.BooleanField(default=False)),
                ('multiple_selection', models.BooleanField(default=True)),
                ('allow_search', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_email', models.BooleanField(default=False)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_link', models.URLField()),
                ('message', models.CharField(default='Thank your for completing this survey', max_length=500)),
                ('button_text', models.TextField(default='Button', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LongText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_character', models.PositiveIntegerField(default=100)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('place_holder', models.CharField(default='PlaceHolder', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min', models.PositiveIntegerField(blank=True, null=True)),
                ('max', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('domain', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('check_number', models.BooleanField(default=False)),
                ('format_number', models.BooleanField(default=True)),
                ('placeholder', models.CharField(default='Placeholder', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PictureChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('super_size', models.BooleanField(default=False)),
                ('multiple_selection', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ratings_length', models.PositiveIntegerField(default=5)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectWithUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('message', models.TextField(blank=True, default='Redirect to url', max_length=1000, null=True)),
                ('custom_html', models.TextField(blank=True, max_length=10000, null=True)),
                ('click_option', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Click here if you are not redirected.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_character', models.PositiveIntegerField(default=100)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
                ('place_holder', models.CharField(default='PlaceHolder', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('accept_url_with', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeScreen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('label', models.TextField(max_length=2000, null=True)),
                ('have_continue_button', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Start Questionaire.', max_length=50, null=True)),
                ('background_image', models.URLField(null=True)),
                ('custom_html', models.TextField(max_length=20000, null=True)),
                ('time_to_complete', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('allow_reselect', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChoicesOptions',
            fields=[
                ('option', models.CharField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.choices')),
            ],
        ),
        migrations.CreateModel(
            name='DropDownOpions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop_down', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.dropdown')),
            ],
        ),
        migrations.CreateModel(
            name='EndScreenSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('social_media_link', models.URLField()),
                ('media_type', models.TextField(choices=[('instagram', 'INSTAGRAM'), ('facebook', 'FACEBOOK'), ('whatsapp', 'WHATSAPP'), ('twitter', 'TWITTER'), ('email', 'EMAIL'), ('tiktok', 'TIKTOK')], default='email', max_length=20)),
                ('end_screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.endscreen')),
            ],
        ),
        migrations.CreateModel(
            name='PictureChoiceImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('alt_tag', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('saturation', models.PositiveIntegerField(default=0)),
                ('contrast', models.PositiveIntegerField(default=0)),
                ('brightness', models.PositiveIntegerField(default=0)),
                ('blur', models.PositiveIntegerField(default=0)),
                ('x', models.PositiveIntegerField(default=1)),
                ('y', models.PositiveIntegerField(default=1)),
                ('hue', models.PositiveIntegerField(default=1)),
                ('grayscale', models.PositiveIntegerField(default=0)),
                ('pixelate', models.PositiveIntegerField(default=0)),
                ('rotationIndex', models.PositiveIntegerField(default=0)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.picturechoice')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyBlockType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField(max_length=250, null=True)),
                ('block_type', models.TextField(choices=[('ConatctInfo', 'ContactInfo'), ('Email', 'Email'), ('PhoneNumber', 'PhoneNumber'), ('Website', 'Website'), ('Choices', 'Choices'), ('DropDown', 'DropDown'), ('PictureChoice', 'PictureChoice'), ('YesNo', 'YesNo'), ('Rating', 'Rating'), ('LongText', 'LongText'), ('ShortText', 'ShortText'), ('Time', 'Time'), ('Date', 'Date'), ('Number', 'Number'), ('QuestionGroup', 'QuestionGroup'), ('EndScreen', 'EndScreen'), ('RedirectToURL', 'RedirectToURL'), ('WelcomeScreen', 'WelcomeScreen')], default='ShortText')),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('label', models.TextField(blank=True, max_length=5000, null=True)),
                ('index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('choices', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices_blocks', to='surveys.choices')),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_blocks', to='surveys.date')),
                ('dropdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_blocks', to='surveys.dropdown')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_blocks', to='surveys.email')),
                ('end_screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_screen_blocks', to='surveys.endscreen')),
                ('long_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_text_blocks', to='surveys.longtext')),
                ('number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number_blocks', to='surveys.number')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_number_blocks', to='surveys.phonenumbers')),
                ('picture_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture_choice_blocks', to='surveys.picturechoice')),
                ('ratings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_blocks', to='surveys.rating')),
                ('redirect_with_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_with_url_blocks', to='surveys.redirectwithurl')),
                ('short_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_text_blocks', to='surveys.shorttext')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('background_color', models.CharField(max_length=50, null=True)),
                ('background_image', models.URLField(null=True)),
                ('survey_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype')),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=250)),
                ('status', models.TextField(choices=[('DEVELOPMENT', 'DEVELOPMENT'), ('PRODUCTION', 'PRODUCTION')], default='DEVELOPMENT', max_length=15)),
                ('show_time_to_complete', models.BooleanField(default=False)),
                ('show_number_of_submissions', models.BooleanField(default=False)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('response_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('survey_is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', models.TextField(choices=[('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='GREEN', max_length=10)),
                ('button', models.TextField(choices=[('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW')], default='GREEN', max_length=10)),
                ('font_size', models.TextField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default='MEDIUM', max_length=10)),
                ('font_family', models.TextField(choices=[('SYSTEM', 'SYSTEM'), ('ARIAL', 'ARIAL'), ('FUTURA', 'FUTURA'), ('HELVETIA', 'HELVETIA'), ('GARAMOND', 'GARAMOND'), ('JOSEFIN_SANS', 'JOSEFIN_SANS'), ('TIMES_NEW_ROMAN', 'TIMES_NEW_ROMAN')], default='SYSTEM', max_length=50)),
                ('border_radius', models.TextField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default='MEDIUM', max_length=10)),
                ('button_text', models.TextField(choices=[('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='WHITE', max_length=10)),
                ('background_color', models.TextField(choices=[('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('WHITE', 'WHITE')], default='WHITE', max_length=10)),
                ('background_pattern', models.TextField(choices=[('pattern-uvskajs', 'pattern-uvskajs'), ('pattern-euukzq', 'pattern-euukzq'), ('pattern-ahwmak', 'pattern-ahwmak'), ('pattern-ydfyai', 'pattern-ydfyai'), ('pattern-arywav', 'pattern-arywav'), ('pattern-arraaj', 'pattern-arraaj'), ('Non', 'Non')], default='Non', max_length=40)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_blocks', to='surveys.surveys'),
        ),
        migrations.CreateModel(
            name='LastUsedBlocks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('block_type', models.TextField(blank=True, choices=[('ConatctInfo', 'ContactInfo'), ('Email', 'Email'), ('PhoneNumber', 'PhoneNumber'), ('Website', 'Website'), ('Choices', 'Choices'), ('DropDown', 'DropDown'), ('PictureChoice', 'PictureChoice'), ('YesNo', 'YesNo'), ('Rating', 'Rating'), ('LongText', 'LongText'), ('ShortText', 'ShortText'), ('Time', 'Time'), ('Date', 'Date'), ('Number', 'Number'), ('QuestionGroup', 'QuestionGroup'), ('EndScreen', 'EndScreen'), ('RedirectToURL', 'RedirectToURL'), ('WelcomeScreen', 'WelcomeScreen')], null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_progress_bar', models.BooleanField(default=True)),
                ('show_question_number', models.BooleanField(default=True)),
                ('free_form_navigation', models.BooleanField(default=True)),
                ('schedule_close_date', models.BooleanField(default=False)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('set_response_limit', models.BooleanField(default=False)),
                ('response_limit', models.PositiveIntegerField(default=10000)),
                ('set_close_message', models.BooleanField(default=False)),
                ('close_message', models.TextField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
        ),
        migrations.CreateModel(
            name='UserReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField(default=list)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_blocks', to='surveys.website'),
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='welcome_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome_screen_blocks', to='surveys.welcomescreen'),
        ),
        migrations.AddField(
            model_name='surveyblocktype',
            name='yes_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yes_no_blocks', to='surveys.yesno'),
        ),
        migrations.CreateModel(
            name='SurveyLogic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('operator', models.TextField(blank=True, choices=[('eq', 'eq'), ('ne', 'eq'), ('gt', 'gt'), ('lt', 'lt'), ('includes', 'includes'), ('not_include', 'not_include')], null=True)),
                ('value', models.CharField(max_length=200)),
                ('endFunction', models.TextField(blank=True, choices=[('goto', 'goto'), ('disable_btn', 'disable_btn')], null=True)),
                ('endValue', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fallBack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fallBack_modal', to='surveys.surveyblocktype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyblocktype')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveys')),
            ],
            options={
                'unique_together': {('field', 'survey')},
            },
        ),
    ]
