# Generated by Django 5.0.4 on 2024-05-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_emailverification_expires_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususer',
            name='completed_quiz',
        ),
        migrations.RemoveField(
            model_name='attemptedquizbyanonymoususer',
            name='attempted_by',
        ),
        migrations.RemoveField(
            model_name='attemptedquizbyanonymoususer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='attemptedquizbyanonymoususer',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='attemptedquizofuser',
            name='attempted_by',
        ),
        migrations.RemoveField(
            model_name='attemptedquizofuser',
            name='questions_answered_by_student',
        ),
        migrations.RemoveField(
            model_name='attemptedquizofuser',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='germanoptions',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='objectiveoptions',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_id',
        ),
        migrations.RemoveField(
            model_name='quizreports',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='host',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizaccesstoken',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='savedquiz',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizreports',
            name='quiz',
        ),
    ]
