# Generated by Django 5.0.4 on 2024-05-01 00:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_anonymoususer_completed_quiz_and_more'),
        ('communities', '0002_alter_posts_quiz'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quiz.quiz'),
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizreports',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedquiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='user',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 1, 3, 56, 134162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 0, 48, 56, 134162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 1, 3, 56, 133164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='next_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 0, 39, 26, 133164, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teachersaccount',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
        migrations.DeleteModel(
            name='AttemptedQuizByAnonymousUser',
        ),
        migrations.DeleteModel(
            name='AttemptedQuizOfUser',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='GermanOptions',
        ),
        migrations.DeleteModel(
            name='ObjectiveOptions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizAccessToken',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizReports',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.DeleteModel(
            name='SavedQuiz',
        ),
        migrations.DeleteModel(
            name='ScoreBoard',
        ),
    ]
